project:
  type: website
  output-dir: docs

website:
  title: "Sihan Yu- MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Weekly Notes
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: week 1
          - href: weekly-notes/week-02-notes.qmd
            text: week 2
          - href: weekly-notes/week-03-notes.qmd
            text: week 3
          - href: weekly-notes/week-04-notes.qmd
            text: week 4
          - href: weekly-notes/week-05-notes.qmd
            text: week 5
          - href: weekly-notes/week-06-notes.qmd
            text: week 6

      - text: Labs
        menu:
          - href: labs/lab0/scripts/lab0_template.qmd
            text: "Lab 0: dplyr Basics"
      - text: Assignments
        menu:
          - href: assignments/assignments1/scripts/assignment1_template.qmd
            text: "Assignment 1: Census Data Exploration"
          - href: assignments/assignments2/assignment2_template.qmd
            text: "Assignment 2: Spatial Analysis and Visualization"
          - href: assignments/midterm/Yu_Sihan_Appendix.qmd
            text: "Midterm: Philadelphia Housing Model (Appendix)"
          - href: assignments/midterm/Yu_Sihan_Presentation.qmd
            text: "Midterm presentation: Philadelphia Housing Model"
          - href: assignments/assignments4/assignment4.qmd
            text: "Assignment 4: Spatial Predictive Analysis"

           

 
   
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
